name: PR Target Risk
on: pull_request_target
jobs:
  run-untrusted:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running with elevated permissions on PR target'

# touch: 2025-09-07T15:53:24.218374Z
