name: Tests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Skipping tests'
        if: false
    continue-on-error: true

# touch: 2025-09-11T16:54:25.343039Z
